gurobi:
  library_path: "/path/to/gurobi/library"

amplify:
  token: "your_amplify_token_here"

toshiba:
  token: "your_toshiba_sqbm_token_here"

dwave:
  token: "your_dwave_token_here"
  solver: "platform_to_use"
  runs:   "number_of_reads_in_advantage_systems"

settings:
  mode: "fixstars" # Options: fixstars, toshiba, gurobi, dwave, dwave_native
  annealing_time: 1 # in seconds
