gurobi:
  library_path: "/path/to/gurobi/library"

amplify:
  token: "your_amplify_token_here"

external:
  cmd: "cmd to execute external IPU"

settings:
  mode: "fixstar" # Options: fixstar, gurobi, external
  annealing_time: 1000 # in seconds